startRecord erroring when starting conference
Howdy Dave!

I've found that using conference.startRecording crashes due to this regex not properly handling the result. When I run it, I get a result like this:
```
Error: +OK Record file rtmp://vida.live/enhanced/05f7cda210ff4ea49122aea69ae595b3 canvas 1
```

Notice the `+OK`. That seems to trip up your regex which causes the crash.